@id=0c996d8c-a4c5-425e-b807-57cd1a7efdb1

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "test",
    "username": "testing",
    "email": "testing@test.com",
    "password": "string"
}
###
###
GET http://localhost:8080/users/{{id}}
Content-Type: application/json
###
